sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.2"
  - development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix js
  - haxelib run travix flash
  - haxelib run travix php
  - haxelib run travix node
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix lua
  - haxelib run travix java
  - haxelib run travix cs
  - haxelib run travix cpp -lib hxcpp

after_success:
  - haxelib run travix release